### PR TITLE
Added restaurant and database producers plus tests

### PR DESCRIPTION
**Pull request by RobertOlvisSmoothstack**

### CODE REVIEW

**Comment by psamsotha-ss** [comment]
So these are the things that I see need to be fixed/changed

- [ ] Code needs to be tested with H2
- [ ] Code needs to use `jaydebeapi`. Currently it's still using `pymysql`
- [ ] Assume tests are run from the root of the project. File paths need to be fixed. Tests will be run with `pytest ./test`
- [ ] Need confirmation to continue to insert items. [Use this helper function](https://github.com/bandwidth-brothers/ss-scrumptious-data-producers/blob/99b2a85b2e8c259c2a7afdb9bf77136e9d833b6d/app/producers/users.py#L174) so the UX is uniform
- [ ] Add a `__str__()` function to the model classes (like the ones in User and Order) so when they print, it is all uniform;
- [ ] Take `.env` off `.gitignore`.

You should pull in the changes from the `dev` branch to get all the up-to-date code. You do not need to merge the `main` branch. We are working off the `dev` branch now.

**Comment by RobertOlvisSmoothstack** [comment]
Shouldn't `.env` be in `.gitignore`? `.env` is typically used to store secrets, so it's common practice to keep it off GitHub and have a file like `example.env` instead.

**Comment by psamsotha-ss** [comment]
Well the username, password, and url won't be the same for this development database and the production one. And environment variables provided on the command line will overwrite the ones in the the `.env` file. If we remove the file, we will force the users to have to put the  `DATABASE_JAR` and the `DATABASE_DRIVER`. This should be something already provided by the program. Or we can use some other means of providing the jar and driver.

**Comment by RobertOlvisSmoothstack** [comment]
Closed as more up to date code is being pulled in via other PRs

**Pull request closed without merging**
